name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check syntax
        run: python -m py_compile main.py

      - name: Run unit tests
        run: python -m unittest discover -s unit_tests -p "test*.py" -v 

      - name: Create artifact file
        run: | 
          mkdir -p artifacts
          echo "CI ran successfully" > artifacts/report.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: my-artifact
         path: artifacts/

      - name: Print artifact info
        run: echo "Artifact 'my-artifact' uploaded. Download it from the Actions tab."
